name: CI flow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-20.04

    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
      IMAGE_NAME: dummy-app

    steps:
    - uses: actions/checkout@v2
    - name: Set Version
      run: |
        echo "VERSION=`cat version-base.txt`.${{ github.run_number }}" >> $GITHUB_ENV
    - name: Build the Docker image
      run: |
        echo ${VERSION} > version.txt
        docker build -t ${IMAGE_NAME}:${VERSION} .

    - name: List values files
      id: finding-files
      working-directory: ./helm-chart
      run: |
          echo "::set-output name=VALUESFILELIST::$(find . -name 'values-*.yaml' -print)"
    - name: Helm lint
      working-directory: ./helm-chart/
      run: |
        IFS="," read -a myarray <<< ${{ steps.finding-files.outputs.VALUESFILELIST }}
        for f in "${myarray[@]}"; do helm lint -f $f ${IMAGE_NAME}; done

    - name: Push to ECR
      id: ecr
      uses: jwalton/gh-ecr-push@v1
      with:
        access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: eu-west-1
        image: ${IMAGE_NAME}:${VERSION}

    - name: Create Tag
      if: ${{ job.status }} == "success"
      uses: anothrNick/github-tag-action@1.33.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CUSTOM_TAG: ${VERSION}

    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: general
        SLACK_COLOR: ${{ job.status }} # or a specific color like 'green' or '#ff00ff'
        # SLACK_ICON: https://github.com/rtCamp.png?size=48
        SLACK_MESSAGE: Job ${GITHUB_JOB} has finished with status ${{ job.status }}
        SLACK_USERNAME: liyaka
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      if: always()
